### PR TITLE
Jmoldon patch

### PR DESCRIPTION
**Pull request by jmoldon**
Just minor clarifications in the READMEs and a suggestion to change conda_env by environment, because that is the default name and it is automatically accepted by things lime myBinder.

I will have more suggestions when I manage to finish the processing

### CODE REVIEW

**Comment by jmoldon** [comment]
@jonesmg good, now with the change of environemnt.yml the repo works in myBinder! https://mybinder.org/v2/gh/AMIGA-IAA/hcg_hi_pipeline/HEAD

Of course, neither casa nor au are installed, but it is good to have that possibility.

I see that for [hcg_global_hi_analysis](https://github.com/AMIGA-IAA/hcg_global_hi_analysis) you have done the same, and now it can be accessed with https://mybinder.org/v2/gh/AMIGA-IAA/hcg_global_hi_analysis/HEAD and you can explore the notebooks.

**Comment by sebastian-luna-valero** [comment]
We could containerise `casa` and try to run it with `udocker` (it was done for `hcg-16`). However, would it make sense to run this on myBinder, with very limited amount of CPU, RAM and storage?

Sorry, I don't now what `au` is!

**Comment by jonesmg** [comment]
I agree that in this case it probably doesn't make much sense to try to run this stuff on myBinder, but I guess it's good to allow the possibility in theory (as Javier said). So I don't think it's worth investing the time to get this to work in containers, but maybe it will make more sense for some future project that might fork this repo or something.

PS: AU is just additional CASA analysis utilities which is a separate library that's required.

**Comment by jmoldon** [comment]
I agree that it is not worth putting more effort to make it fully executable in my Binder. The change in environment.yml was easy enough and allows you to run the notebooks and the plots, and that is enough.

A couple of points regarding future use of binder: first, myBinder has increased significantlly the resources allocated to the virtual machines, so getting full processing of **old** and small data set may start to be possible. On the other hand, we are currently working on deploying a binderhub service at the spsrc, which would provide the same automatic deployment as myBinder, but with all the resources we can allocate. That is another interesting option for the future.

**Comment by sebastian-luna-valero** [comment]
Eager to see the BinderHub service at the SPSRC!

This is also in beta testing at the moment: https://binder.notebooks.egi.eu/ and may also help in the same regard.

**Pull request merged**
